services:

  pg:
    image: postgres:16
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5439:5432"

  app:
    build: .
    container_name: office_app
    ports:
      - "8045:8045"
    env_file:
      - .env
    depends_on:
      - pg
    restart: always

volumes:
  pgdata:
